os: linux
sudo: required
language: python
install:
  - pip install -r requirements.txt
matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
      dist: trusty
    - python: 3.3
      dist: trusty
    - python: 3.2
      dist: trusty
    - python: 2.7
      dist: trusty
script: python yapi.py install test
