os: linux
sudo: required
language: python
install:
  - pip install -r requirements.txt
matrix:
  include:
    - python: 3.7
      dist: xenial
      env:
        - PACKAGE=test
    - python: 3.7
      dist: xenial
      env:
        - PACKAGE=updateYapiScripts
    - python: 3.6
      dist: trusty
      env:
        - PACKAGE=test
    - python: 3.6
      dist: trusty
      env:
        - PACKAGE=updateYapiScripts
    - python: 3.5
      dist: trusty
      env:
        - PACKAGE=test
    - python: 3.5
      dist: trusty
      env:
        - PACKAGE=updateYapiScripts
    - python: 3.4
      dist: trusty
      env:
        - PACKAGE=test
    - python: 3.4
      dist: trusty
      env:
        - PACKAGE=updateYapiScripts
before_script: python install.py --lang=en --softlink=no
script: python yapi.py install $PACKAGE

notifications:
    slack: yapiworkspace:Rh3wlsbST5hm2JtSi3l3BpZO
